### PR TITLE
added priorities

### PR DESCRIPTION
**Pull request by vdiez**
still didn't have time to test. Please let me know what do you think of this approach for queues priorities

### CODE REVIEW

**Comment by floatdrop** [comment]
@vdiez I guess it will be more efficient to store all tasks in array in form of `{priority: 10, task: X}` and sort it by `priority` property. This will reduce `size` and `next` complexity to `O(1)`, get rid of `queue` property inflating and do actually priority sorting (because JavaScript iterates properties in order of addition - try to add tasks with properties 2, 1, 0 and see).

**Comment by vdiez** [comment]
See your point. I think it really depends on the use case. If the amount of tasks in the queue is expected to be very high and just some priorities I expect this version to be more efficient. Also, note that I'm not using an object but a multidimensional array.

As a side-note, ECMAScript does not define an order of iteration on object properties and algorithms should not rely on that assumption. There are [interesting discussions](https://bugs.chromium.org/p/v8/issues/detail?id=164) about this.

**Comment by floatdrop** [comment]
> Also, note that I'm not using an object but a multidimensional array.

Yeah, misread that.

> I think it really depends on the use case.

Well, in general case we have one common priority and some rare extra – after high priority tasks will be exaughsted you will still have for loop iterating over empty priority buckets. So you paying on every take from queue some extra cost.

Draw back is that you will have sorting on each insert into queue, but it should take `O(log n)` time (array is already sorted).

P.s. and this will enable non-integer priorities, which could be nice to have.

**Comment by pornel** [comment]
Regarding specifically that implementation, I'd add rounding (in case user computes priority, e.g. by averaging some factors) and limit allowed values to sensible range, because `add(…, 99999)` shouldn't be that costly. Cocoa has [5 levels](https://developer.apple.com/reference/foundation/nsoperationqueuepriority).

Overall I don't know if that's the best solution, because I don't know what are intended tradeoffs of this library — how much complexity is allowed? How much flexibility is intended? 

This approach is probably on the good side of 80/20 rule, but I can come up with use cases that are beyond that (e.g. priority changes after the item has been added to the queue).

So I wonder if it can be generalized so that problem of prioritization is not hardcoded in the library, but can be supplied by the user, e.g. provide callbacks to

* `enqueue(task, options)`
* `task = dequeue()`

and this would allow pluggable implementations - from simple queue as an array, to fancy heaps that support dynamically changing priorities, to special ones like picking random element or LIFO.

**Comment by floatdrop** [comment]
@pornel Cocoa exposing constants, but priority can be any `int`:

```cpp
typedef NS_ENUM(NSInteger, NSOperationQueuePriority) {
    NSOperationQueuePriorityVeryLow = -8L,
    NSOperationQueuePriorityLow = -4L,
    NSOperationQueuePriorityNormal = 0,
    NSOperationQueuePriorityHigh = 4,
    NSOperationQueuePriorityVeryHigh = 8
};
```

Specifying random priorities should not slow down queue – I'm quite sure this is important requirement.

**Comment by pornel** [comment]
Other priority values are [rounded to the nearest valid priority](https://developer.apple.com/reference/foundation/nsoperation/1411204-queuepriority?language=objc#discussion).

Cocoa also has a concept of [dependencies between tasks](https://developer.apple.com/reference/foundation/operation/1412859-adddependency) and IIRC this works even across queues. I use that in ImageOptim, although I think it can be emulated by appropriately enqueuing tasks "manually".

**Comment by floatdrop** [comment]
@pornel oh god, why 😅

Okay, let's expose API to define custom queues.

@vdiez are you okay with this?

**Comment by vdiez** [comment]
Well, I think that would be nice as optional parameters to the constructor. By default, it should still provide such behaviour and while I agree the cost of size and next is still to be improved, a single queue of objects does not convince me either. My use case is ~10k items in the queue with just two priorities, that why I'm quite stubborn in this subject.

Probably using object of where the keys are the priorities, so we avoid the cost of `add(..., 9999)` as mentioned. But then we should define what's the order of the priorities if any alphanumeric is allowed.

Or no default behaviour, queue is external to the library and is up to the user to provide it, as you said, but don't you think the library would be oversimplified?

**Comment by pornel** [comment]
I think it'd be a good path to figure out what's needed:

1. Add API for any queue implementation (as constructor argument)
2. By default provide implementation of a single queue without priorities
3. Wait and see what other implementations people write themselves
4. Eventually bundle most popular ones in the library

**Comment by floatdrop** [comment]
@pornel can you check for API #4?

**Comment by vdiez** [comment]
Cancelled due to improvements on #4

**Pull request closed without merging**
