### PR TITLE
Add `pauseOnError` option

### LINKED ISSUE #29: Rejecting the whole queue when a task rejects
I'm trying `p-queue` after using [`promise-queue`](https://www.npmjs.com/package/promise-queue) for some time. Given this background, I was expecting to see the whole queue failing if any of its tasks rejects. However, this does not seem to happen.

Here's an example:

```js
// testPQueue.js

import * as PQueue from "p-queue";

async function processQueue() {
  const queue = new PQueue();
  queue.add(
    () =>
      new Promise((resolve, reject) =>
        setTimeout(() => {
          reject();
        }, 500),
      ),
  );

  await queue.onIdle();
  console.log("should not be here");
  return 42;
}

(async () => {
  try {
    const result = await processQueue();
    console.log(result);
  } catch (e) {
    console.log("could not process queue");
  }
})();
```

```
node ./testPQueue.js
```

Instead of seeing `could not process queue` in my `stdout`, I get this:

```
should not be here
42
(node:13679) UnhandledPromiseRejectionWarning: undefined
(node:13679) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13679) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

How can I stop and reject the whole queue once any its tasks has failed?

### PR DESCRIPTION
**Pull request by szmarczak**
Fixes #29

### CODE REVIEW

**Comment by sindresorhus** [comment]
I'm still not sold on this as being a good solution. I think we need more discussion in #29.

**Comment by szmarczak** [comment]
Indeed.

**Comment by sindresorhus** [comment]
I'm going to close this as I still don't think such an option is the right approach.

**Comment by szmarczak** [comment]
Fair enough. People can catch the error and pause the queue manually though. It's just a simple try / catch.

**Pull request closed without merging**
