### PR TITLE
Correct the documented default for the `throwOnTimeout` option

### LINKED ISSUE #74: Timeout documentation and questions
Hi there:

Thanks for this project, really appreciate it, and I'm getting some excellent use out of it.

Is it intended for throwOnTimeout to default to true as declared in the README?

I notice the default is actually false in the implementation and it must be explicitly enabled.

It would likely be a rather rough breaking change for some people to modify that to an opt-out instead of opt-in, so I'm guessing the documentation should be updated instead?

Also, I'm not clear how the "timeout per operation functionality is supposed to function - is it intended to be settable at queue time, e.g. `schedule.add(() => <promise>, {timeout: <timeout>})`

I believe there's likely something broken in the option overrides if that's the case, as currently it doesn't seem to have any impact whatsoever. It looks like a fairly easy change to introduce though.

### PR DESCRIPTION
**Pull request by EricMCornelius**
See questions in #74 - this is one possible option with a test and documentation fix for the throwOnTimeout default.

I'm not well-versed in typescript, but it seems like there's probably a better means for optional parameter lookups than this?

Fixes #74

### CODE REVIEW

**Comment by sindresorhus** [comment]
You want `options?: EnqueueOptionsType` => `options?: EnqueueOptionsType = {}` on line 211

If you add a default parameter, you won't have to deal with undefined in all the places.

**Comment by EricMCornelius** [comment]
@sindresorhus - after that change I get the following error. Getting flashbacks to my C++ template metaprogramming days:

```
source/index.ts:211:54 - error TS2322: Type '{}' is not assignable to type 'EnqueueOptionsType'.
  '{}' is assignable to the constraint of type 'EnqueueOptionsType', but 'EnqueueOptionsType' could be instantiated with a different subtype of constraint 'QueueAddOptions'.
```

**Comment by EricMCornelius** [comment]
Forcibly casting the options or default on the next line seems to work fine though, unclear what the type system intent is here.

**Comment by sindresorhus** [comment]
I'm not sure myself. The constraints for the options seem needlessly complicated.

@ltetzlaff Any way we could use `options?: EnqueueOptionsType = {}` here?

**Comment by ltetzlaff** [comment]
https://github.com/EricMCornelius/p-queue/pull/1 ✌️

**Pull request merged**
