### PR TITLE
Make `.start()` return the instance

### LINKED ISSUE #56: Return a promise from start()?
When queue is created with `autoStart: false`, I found it common to call:

```
queue.start();
await queue.onIdle();
```

I wonder if it would make sense to add a call to `onIdle` at the end of `start()` method so that just one could be used to start and wait for all tasks?

### PR DESCRIPTION
**Pull request by Rafael09ED**
Fixes #56 
Helper function for .start() returning .onIdle()

### CODE REVIEW

**Comment by sindresorhus** [comment]
I dunno. I don't find it very obvious that `await queue.start();` waits for onIdle. I think it would be better to return `this`, so you could do `await queue.start().onIdle();` that would be more flexible and more readable.

**Comment by szmarczak** [comment]
I agree with @sindresorhus

**Comment by sindresorhus** [comment]
@Rafael09ED Can you update the PR for my previous comment?

**Comment by Rafael09ED** [comment]
Seems issue #66 is the reason for failed checks

**Pull request merged**
